// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr_Jp9ONUZqCD18WMZyAXMMluZGLIi9VU',
    appId: '1:362725516540:web:5f00bfc350009eb6b7a379',
    messagingSenderId: '362725516540',
    projectId: 'cocodemy-77295',
    authDomain: 'cocodemy-77295.firebaseapp.com',
    storageBucket: 'cocodemy-77295.appspot.com',
    measurementId: 'G-3K5HM0F7J0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAhON5RSPo3PbOq_MV4rLf1lfbfYO68EQ',
    appId: '1:362725516540:android:6b6baf2291be5ee3b7a379',
    messagingSenderId: '362725516540',
    projectId: 'cocodemy-77295',
    storageBucket: 'cocodemy-77295.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiKCXh7csY9VOws3C3JP8cXeEYoUXLQbA',
    appId: '1:362725516540:ios:118b70c048187da1b7a379',
    messagingSenderId: '362725516540',
    projectId: 'cocodemy-77295',
    storageBucket: 'cocodemy-77295.appspot.com',
    iosClientId: '362725516540-v19gda38oci78351s3j0rt6k1euc66jk.apps.googleusercontent.com',
    iosBundleId: 'com.example.cocodemy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiKCXh7csY9VOws3C3JP8cXeEYoUXLQbA',
    appId: '1:362725516540:ios:118b70c048187da1b7a379',
    messagingSenderId: '362725516540',
    projectId: 'cocodemy-77295',
    storageBucket: 'cocodemy-77295.appspot.com',
    iosClientId: '362725516540-v19gda38oci78351s3j0rt6k1euc66jk.apps.googleusercontent.com',
    iosBundleId: 'com.example.cocodemy',
  );
}
